### ISSUE TITLE
创业从0到1！ | Mockmain

### ISSUE THREAD

**Issue by tangly1024** [tangly1024/tlyong1992.github.io#1]
https://tlyong1992.github.io/2019/04/16/start-an-undertaking/ 

 关于创业现状目前我在一家startup上班，平时做服务端JAVA开发，服务器部署、运维，数据库设计，接口设计，后台管理页面开发(基于Vue前后端分离)，同时涉猎一些产品设计相关，偶尔用用axure，操心一下app开发的交互逻辑和动效。
目前

**Comment by tlyong1992** [comment]
测试评论
